services:
  - type: web
    name: veloza-motors-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
